export const event = {
    SET_PRODUCTS:"SET_PRODUCTS",
    SELECT_PRODUCT:"SELECTED_PRODUCT",
    REMOVE_PRODUCT:"REMOVE_PRODUCT",
    ADD_TO_CART:"ADD_TO_CART",
    EMPTY_CART:"EMPTY_CART",
    REMOVE_CART_PRODUCT:"REMOVE_CART_PRODUCT"
}